<a href="https://colab.research.google.com/github/varunofficial2509/ineuron-ML/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [4]:
import numpy as np

In [20]:
def vandermode(inputvector, n , increase):
    if (increase==False):
        output = np.array([x**(n-i-1) for x in inputvector for i in range(n)]).reshape(inputvector.size, n)
    elif (increase==True):
        output = np.array([x**i for x in inputvector for i in range(n)]).reshape(inputvector.size,n)
        
    return output



In [21]:
ip = np.array([1,2,3,4,5])
column = 3
dec_order = vandermode(ip,column,False)
inc_order = vandermode(ip,column,True)

print('The input vector :',ip,'\n')
print('the no. of columns : ', column , "\n")
print('Increasing Order : ', "\n" , dec_order, "\n")
print('Increasing Order : ',"\n", inc_order , "\n")



The input vector : [1 2 3 4 5] 

the no. of columns :  3 

Increasing Order :  
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Increasing Order :  
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 




Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [22]:
import numpy as np
def average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(average(a, n=3))


[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
